ads/urls.py
from django.conf.urls import url

from ads import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^register/$', views.registr_view, name='reg'),
    url(r'^adverts/$', views.AdvertList.as_view(), name='advert_list'),
    url(r'^advert_create/$', views.AdvertCreate.as_view(), name='advert_create'),
    url(r'^advert_delete/$', views.advert_delete, name='advert_delete'),
    url(r'^advert_stop/$', views.advert_stop, name='advert_show'),

    url(r'^billboard_stop/$', views.billboard_stop, name='billboard_show'),
    url(r'^billboard_delete/(?P<pk>[0-9]+)/$', views.billboard_delete, name='billboard_delete'),
    url(r'^billboard_create/$', views.billboard_create_view, name='billboard_create'),
    url(r'^billboard_update/(?P<pk>[0-9]+)/$', views.billboard_update, name='billboard_update'),
    url(r'^billboards/$', views.billboard_list, name='billboard_list'),

    url(r'^advert_accept/$', views.advert_accept, name='advert_accept'),
    url(r'^set_cookie/$', views.set_cookie, name='view_cookie'),
    url(r'^advert_favorite/$', views.advert_favorite, name='advert_favorite'),
    url(r'^favorites/$', views.FavoriteView.as_view(), name='favorite_view'),
    url(r'^vip/$', views.vip, name='vip'),
    url(r'^allotted/$', views.allotted, name='allotted'),
    url(r'^up_list/$', views.up_list, name='up_list'),
    url(r'^f_search/$', views.f_search, name='f_search'),
    url(r'^search/$', views.search, name='search'),
    url(r'^click_count/$', views.click_count, name='click_count'),
    url(r'^contacts/$', views.Contacts.as_view(), name='contacts'),
    url(r'^terms/$', views.Terms.as_view(), name='terms'),
    url(r'^advertising/$', views.Advertising.as_view(), name='advertising'),
    url(r'^shop_create/$', views.ShopCreateView.as_view(), name='shop_create'),
    url(r'^shop_status/$', views.shop_status, name='shop_status'),
    url(r'^shops/$', views.ShopListView.as_view(), name='shop_list'),
    url(r'^multiple/$', views.advert_photo_upload, name='advert_photo_upload'),
    url(r'^delete_advert_photo/$', views.advert_photo_delete, name='advert_photo_delete'),
    url(r'^shop_payment/$', views.shop_payment, name='shop_payment'),
    url(r'^metro_load/$', views.metro_load, name='metro_load'),
    url(r'^county_load/$', views.county_load, name='county_load'),
    url(r'^shop/(?P<alias>[\w-]+)/$', views.ShopDetailView.as_view(), name='shop_detail'),
    url(r'^shop/(?P<alias>[\w-]+)/edit/$', views.ShopUpdateView.as_view(), name='shop_update'),
    url(r'^(?P<url_name>.+)/(?P<pk>[0-9]+)/$', views.AdvertDetail.as_view(), name='advert_detail'),
    url(r'^(?P<url_name>.+)/(?P<pk>[0-9]+)/edit/$', views.AdvertUpdate.as_view(), name='advert_update'),
    url(r'^(?P<city>[\w|\W]+)/(?P<category>.+)/$', views.CategoryView.as_view(), name='category_view'),
    url(r'^(?P<city>[\w|\W]+)/$', views.CityFilter.as_view(), name='city_filter'),
]

main/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from main import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('allauth.urls')),
    url(r'^account/profile/', include('authentication.urls', 'profile')),
    url(r'^transaction/', include('transaction.urls')),
    url(r'^', include('ads.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads/models.py
import os

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from .utils import translit


# Create your models here.


class Division(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название раздела')
    url_name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Раздел'
        verbose_name_plural = 'Разделы'

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.url_name = translit(self.name)
        super(Division, self).save()


class Region(models.Model):
    name = models.CharField(max_length=40, unique=True, verbose_name='Название региона')
    url_name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.url_name = translit(self.name)
        super(Region, self).save()

    class Meta:
        verbose_name = 'Регион'
        verbose_name_plural = 'Регионы'


class Metro(models.Model):
    region = models.ForeignKey(Region, verbose_name='Регион')
    name = models.CharField(max_length=60, verbose_name='Название метро')
    url_name = models.CharField(max_length=60)

    class Meta:
        verbose_name = 'Метро'
        verbose_name_plural = 'Метро'
        unique_together = ('region', 'name')

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.url_name = translit(self.name)
        super(Metro, self).save()


class County(models.Model):
    region = models.ForeignKey(Region, verbose_name='Регоин')
    name = models.CharField(max_length=40, verbose_name='Название района')
    url_name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ('region', 'name')
        verbose_name = 'Район'
        verbose_name_plural = 'Районы'

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.url_name = translit(self.name)
        super(County, self).save()


divisions = [
    Division(name='Автомойки, Автосервисы, СТО', url_name=translit('Автомойки, Автосервисы, СТО')),
    Division(name='Автозаправочные станции(АЗС)', url_name=translit('Автозаправочные станции(АЗС)')),
    Division(name='Автосалоны', url_name=translit('Автосалоны')),
    Division(name='Аптеки', url_name=translit('Аптеки')),
    Division(name='Арендный бизнес', url_name=translit('Арендный бизнес')),
    Division(name='Банковская деятельность', url_name=translit('Банковская деятельность')),
    Division(name='Бизнес и Недвижимость за рубежом', url_name=translit('Бизнес и Недвижимость за рубежом')),
    Division(name='Гостиницы, отели, базы отдыха', url_name=translit('Гостиницы, отели, базы отдыха')),
    Division(name='Добыча полезных ископаемых', url_name=translit('Добыча полезных ископаемых')),
    Division(name='Заводы, промышленные помещения', url_name=translit('Заводы, промышленные помещения')),
    Division(name='Коммерческая недвижимость', url_name=translit('Коммерческая недвижимость')),
    Division(name='Медицинские центры и стоматологии', url_name=translit('Медицинские центры и стоматологии')),
    Division(name='Образование', url_name=translit('Образование')),
    Division(name='Продуктовые магазины, супермаркеты', url_name=translit('Продуктовые магазины, супермаркеты')),
    Division(name='Производство', url_name=translit('Производство')),
    Division(name='Развлечения', url_name=translit('Развлечения')),
    Division(name='Рестораны, Кафе, Бары', url_name=translit('Рестораны, Кафе, Бары')),
    Division(name='Салоны красоты', url_name=translit('Салоны красоты')),
    Division(name='Сельское хозяйство', url_name=translit('Сельское хозяйство')),
    Division(name='Сервис и услуги', url_name=translit('Сервис и услуги')),
    Division(name='СМИ', url_name=translit('СМИ')),
    Division(name='Столовые', url_name=translit('Столовые')),
    Division(name='Страховая деятельность', url_name=translit('Страховая деятельность')),
    Division(name='Строительство', url_name=translit('Строительство')),
    Division(name='Телекоммуникации, Интернет - магазины, IT',
             url_name=translit('Телекоммуникации, Интернет - магазины, IT')),
    Division(name='Торговля(оптовая, розничная)', url_name=translit('Торговля(оптовая, розничная)')),
    Division(name='Транспорт и услуги', url_name=translit('Транспорт и услуги')),
    Division(name='Туристический бизнес', url_name=translit('Туристический бизнес')),
    Division(name='Услуги для бизнеса и населения', url_name=translit('Услуги для бизнеса и населения')),
    Division(name='Фитнес центры', url_name=translit('Фитнес центры')),
    Division(name='Прочий бизнес', url_name=translit('Прочий бизнес')),
]

regions = [
    Region(name='Москва', url_name=translit('Москва')),
    Region(name='Санкт-Петербург', url_name=translit('Санкт-Петербург')),
    Region(name='Кемерово', url_name=translit('Кемерово')),
    Region(name='Новокузнецк', url_name=translit('Новокузнецк')),
    Region(name='Ростов-на-Дону', url_name=translit('Ростов-на-Дону')),
    Region(name='Тюмень', url_name=translit('Тюмень')),
    Region(name='Барнаул', url_name=translit('Барнаул')),
    Region(name='Екатеринбург', url_name=translit('Екатеринбург')),
    Region(name='Краснодар', url_name=translit('Краснодар')),
    Region(name='Новосибирск', url_name=translit('Новосибирск')),
    Region(name='Самара', url_name=translit('Самара')),
    Region(name='Уфа', url_name=translit('Уфа')),
    Region(name='Владивосток', url_name=translit('Владивосток')),
    Region(name='Иркутск', url_name=translit('Иркутск')),
    Region(name='Красноярск', url_name=translit('Красноярск')),
    Region(name='Омск', url_name=translit('Омск')),
    Region(name='Сургут', url_name=translit('Сургут')),
    Region(name='Хабаровск', url_name=translit('Хабаровск')),
    Region(name='Волгоград', url_name=translit('Волгоград')),
    Region(name='Казань', url_name=translit('Казань')),
    Region(name='Нижний Новгород', url_name=translit('Нижний Новгород')),
    Region(name='Пермь', url_name=translit('Пермь')),
    Region(name='Томск', url_name=translit('Томск')),
    Region(name='Челябинск', url_name=translit('Челябинск'))
]


def shop_name(instance, filename):
    return '/'.join([instance.alias, filename])


open = 'open'
close = 'close'
status_shop = (
    (open, 'Открытый'),
    (close, 'Закрытый')
)


class Shop(models.Model):
    region = models.ForeignKey(Region, related_name='shops')
    owner = models.OneToOneField(User, related_name='shop', verbose_name='Владелец')
    name = models.CharField(max_length=40, verbose_name='Название магазина')
    alias = models.CharField(max_length=20, unique=True, verbose_name='Ссылка')
    anons = models.CharField(max_length=100, verbose_name='Текст для анонса')
    description = models.TextField(max_length=5000, verbose_name='Описание магазина')
    site = models.URLField(null=True, blank=True, verbose_name='Сайт магазина')
    person = models.CharField(max_length=30, verbose_name='ФИО')
    logo = models.ImageField(upload_to=shop_name, verbose_name='Логотип')
    status = models.CharField(choices=status_shop, max_length=5, verbose_name='Статус')
    video = models.CharField(max_length=50, null=True, blank=True, verbose_name='Видео')
    phones = models.CharField(null=True, blank=True, max_length=17, verbose_name='Телефон')
    mode = models.CharField(max_length=40, null=True, blank=True, verbose_name='График работы')
    address = models.CharField(max_length=255, null=True, blank=True, verbose_name='Адрес')
    skype = models.CharField(max_length=20, null=True, blank=True, verbose_name='Логин skype')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата открытия')
    background = models.ImageField(upload_to=shop_name, null=True, blank=True, verbose_name='Задний фон')
    paid = models.BooleanField(default=False, verbose_name='Оплачен')
    active_days = models.IntegerField(default=0, verbose_name='Количество активных дней')

    class Meta:
        verbose_name = 'Магазин пользователя'
        verbose_name_plural = 'Магазины пользователей'

    def __str__(self):
        return '%s (%s)' % (self.name, self.alias)


class ShopBackground(models.Model):
    image = models.ImageField(upload_to='backgrounds/')

    def image_tag(self):
        return '<img src="%s" style="width: 200px; height: 100px;">' % self.image.url

    image_tag.allow_tags = True

    def __str__(self):
        return self.image.path

    class Meta:
        verbose_name = 'Задний фон магазина'
        verbose_name_plural = 'Задние фоны магазина'


ready = 'ready'
search = 'search'
offer = 'offer'

sectors = (
    (ready, 'Готовый бизнес'),
    (search, 'Поиск инвестиций'),
    (offer, 'Предложения инвесторов'),
)

acts = (
    ('sell', 'Продать'),
    ('buy', 'Купить'),
)

status = (
    ('consideration', 'На рассмотрении'),
    ('rejected', 'Отклонен'),
    ('accepted', 'Разрешен')
)


class PositionManager(models.Manager):
    def max_position(self):
        adverts = Advert.objects.all()
        if adverts:
            position = max(advert.position for advert in adverts)
        else:
            position = 1
        return position


class Favorite(models.Model):
    key = models.CharField(max_length=30, null=True, blank=True)
    user = models.OneToOneField(User, related_name='favorite', null=True, blank=True)


class Advert(models.Model):
    owner = models.ForeignKey(User, related_name='advert', verbose_name='Владелец')
    position = models.IntegerField(null=True, blank=True, default=None)
    region = models.ForeignKey(Region, verbose_name='Регион')

ads/forms.py
# coding=utf-8
from django import forms
from django.contrib.auth.models import User
from django.core import validators

from .models import Advert, Region, sectors, acts, AdvertPhoto, Shop, Division, Billboard


class AdvertCreateForm(forms.ModelForm):
    single_division = forms.ModelChoiceField(Division.objects.all(), empty_label=None, required=False)
    region = forms.ModelChoiceField(Region.objects.all(), empty_label=None)
    type = forms.ChoiceField(choices=sectors)
    act = forms.ChoiceField(choices=acts)
    cost = forms.CharField(max_length=25)
    phone = forms.CharField(
        validators=[validators.RegexValidator(
            r'^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$',
            'Введите правильный номер телефона'
        )],
        label='Номер телефона')

    class Meta:
        model = Advert
        exclude = ['url_name', 'owner', 'active', 'shop', 'solve_reject_text', 'status', 'position', 'cost']

    def clean(self):
        cleaned_data = super(AdvertCreateForm, self).clean()
        # if not cleaned_data.get('multiple_division') and cleaned_data.get('type') == 'offer':
        # raise forms.ValidationError({'multiple_division': 'Выберите хотя бы одну категорию'})
        if not cleaned_data.get('single_division') and cleaned_data.get('type') != 'offer':
            raise forms.ValidationError({'single_division': 'Выберите категорию'})

    def __init__(self, *args, **kwargs):
        instance = kwargs.get('instance', None)
        if instance:
            kwargs.update(initial={
                'cost': instance.cost,
            })
        super(AdvertCreateForm, self).__init__(*args, **kwargs)


class AdvertPhotoForm(forms.ModelForm):
    class Meta:
        model = AdvertPhoto
        fields = ['photo']


PhotoFormSet = forms.inlineformset_factory(Advert, AdvertPhoto, form=AdvertPhotoForm, can_delete=True, max_num=10,
                                           extra=2)


class AdvertAdminForm(forms.ModelForm):
    owner = forms.ModelChoiceField(User.objects.all(), empty_label=None)
    region = forms.ModelChoiceField(Region.objects.all(), empty_label=None)
    type = forms.ChoiceField(choices=sectors)
    act = forms.ChoiceField(choices=acts)

    class Meta:
        model = Advert
        exclude = ['url_name', ]

    def clean(self):
        cleaned_data = super(AdvertAdminForm, self).clean()
        if not cleaned_data.get('multiple_division') and cleaned_data.get('type') == 'offer':
            raise forms.ValidationError({'multiple_division': 'Выберите хотя бы одну категорию'})
        elif not cleaned_data.get('single_division') and cleaned_data.get('type') != 'offer':
            raise forms.ValidationError({'single_division': 'Выберите категорию'})


class ShopCreateForm(forms.ModelForm):
    image = forms.CharField(widget=forms.HiddenInput, required=False)
    region = forms.ModelChoiceField(Region.objects.all(), empty_label=None)

    class Meta:
        model = Shop
        exclude = ['owner', 'status', 'active_days', 'paid']


class BillboardCreateForm(forms.ModelForm):
    region = forms.ModelChoiceField(Region.objects.all(), required=False, empty_label='На всю Россию')

    class Meta:
        model = Billboard
        exclude = ['user', 'shows', 'clicks', 'status', 'show']


class BillboardUpdateForm(forms.ModelForm):
    region = forms.ModelChoiceField(Region.objects.all(), required=False, empty_label='На всю Россию')

    class Meta:
        model = Billboard
        exclude = ['user', 'shows', 'clicks', 'status']

ads/templates/billboard/billboard_create.html
<tr role="row">
    <td class="sorting_1">{{ data.link }}</td>
    <td>{{ data.get_status_display }}</td>
    <td>{{ data.shows }}</td>
    <td>{{ data.clicks }}</td>
    <td><span class="accept" data-id="{{ data.id }}">Разрешить</span></td>
</tr>

ads/templates/billboard/create.html
{% extends 'profile_base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block extra_styles %}
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <style>
        .dropdown-menu{min-height: inherit!important;}
    </style>
{% endblock %}
{% block profile_content %}
    <div class="card-box">
    <div class="row">
        <div class="col-md-12">
            <h2 class="col-md-offset-2" style="margin-bottom: 50px;">{% block form_title %}Создание рекламы на сайте biznesdesk.ru{% endblock %}</h2>
            <form class="form-horizontal" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="" class="col-md-2 control-label">*Выберите регион</label>
                    <div class="col-md-8">
                        {{ form.region|add_class:'selectpicker'|attr:'data-live-search: true'|attr:'data-style: btn-white' }}</div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">*Ссылка</label>
                    {{ form.link.errors }}
                    <div class="col-md-8">
                        {{ form.link|attr:'required'|add_class:'form-control' }}
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label" for="id_block">*Выберите рекламный блок</label>
                    <div class="col-md-2">
                        <select name="block" id="id_block" class="selectpicker" data-style="btn-white">
                            <option value="1" data-width="{{ settings.width_1 }}" data-height="{{ settings.height_1 }}">1 блок
                            </option>
                            <option value="2" data-width="{{ settings.width_2 }}" data-height="{{ settings.height_2 }}">2 блок
                            </option>
                            <option value="3" data-width="{{ settings.width_3 }}" data-height="{{ settings.height_3 }}">3 блок
                            </option>
                            <option value="4" data-width="{{ settings.width_4 }}" data-height="{{ settings.height_4 }}">4 блок
                            </option>
                        </select>
                    </div>
                    <div class="col-md-8">Картинка рекламного блока должна быть <br>
                        Шириной: <span style="color: red" class="w">{{ settings.width_1 }}</span> пикселей <br> Высотой: <span style="color: red" class="h">{{ settings.height_1 }}</span> пикселей.</div>
                </div>
                <div class="form-group">
                    <label for="id_image" class="col-md-2 control-label"></label>
                    <div class="col-md-8">
                        {% if form.instance.pk %}
                            {{ form.image|add_class:'filestyle'|attr:'data-input: false'|attr:'data-buttonname:btn-white' }}
                        {% else %}
                            {{ form.image|add_class:'filestyle'|attr:'required'|attr:'data-input: false'|attr:'data-buttonname:btn-white' }}
                    {% endif %}
                    </div>
                </div>
                {% block update %}
                    <div class="col-md-offset-2" style="margin-bottom: 20px;"><div class="g-recaptcha" data-sitekey="6LfsxggUAAAAAHCPU-x3gsylrixehd2-SKAfSvqo"></div></div>
                {% endblock %}
                {{ form.non_field_errors }}
                <a href="{% url 'profile:general' %}" class="btn btn-default waves-effect waves-light">
                                                   <span class="btn-label"><i class="fa fa-arrow-left"></i>
                                                   </span>Назад в профиль</a>
                    <button type="submit" class="btn btn-inverse waves-effect waves-light">Создать рекламный блок</button>
                    <a href="{% url 'advertising' %}" target="_blank">Условия пользования рекламными блоками</a>
            {% block delete %}{% endblock %}
            </form>
        </div>
    </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'assets/plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/plugins/datatables/dataTables.bootstrap.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap-filestyle/src/bootstrap-filestyle.min.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'assets/plugins/notifyjs/dist/notify.min.js' %}"></script>
    <script src="{% static 'assets/plugins/notifications/notify-metro.js' %}"></script>
    <script src="{% static 'assets/plugins/switchery/dist/switchery.min.js' %}"></script>
    <script>
        function readURL(input, w, h) {
            var reader = new FileReader(), result = false, img = input.files[0];
            reader.onload = function (e) {
                var image = new Image();
                image.src = e.target.result;
                image.onload = function () {
                    result = !(this.width != w || this.height != h);
                    if (!result) {
                        $(input).filestyle('clear');
                        alert('Неправильный размер картинки')
                    }
                };
                return result
            };
            reader.readAsDataURL(img);
        }
        function typeChecker(input, w, h) {
            var file = input.files[0];
            if (!file) {
                return false;
            }
            var type = file.type.split('/')[0];
            if (type == 'image') {
                return readURL(input, w, h);
            } else {
                alert('Только картинки');
                $(input).filestyle('clear')
            }
            return false;
        }
        var $image = $('#id_image'), $block = $('#id_block'), w, h, opt;
        $image.change(function (e) {
            opt = $block.find('option:selected', this);
            w = opt.attr('data-width');
            h = opt.attr('data-height');
            typeChecker(this, w, h)
        });
        $block.change(function () {
            opt = $(this).find('option:selected', this);
            w = opt.attr('data-width');
            h = opt.attr('data-height');
            $('.w').html(w);
            $('.h').html(h);
            typeChecker($image[0], w, h);
        })
    </script>
    {% block update_js %}{% endblock %}
{% endblock %}

ads/templates/billboard/list.html
{% extends 'profile_base.html' %}
{% block profile_content %}
    <div class="card-box">
    <div class="panel-body">
    <table id="datatable_4" class="table table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th>Регион</th>
                                        <th>Изображение</th>
                                        <th>Ссылка</th>
                                        <th>Просмотры</th>
                                        <th>Клики</th>
                                        <th>Статус</th>
                                        <th>действия</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for billboard in objects %}
                                        <tr id="billboard{{ billboard.pk }}">
                                            <td>
                                                {% if billboard.region %}
                                                {{ billboard.region }}
                                                {% else %}
                                                    Вся Россия
                                            {% endif %}
                                            </td>
                                            <td>
                                                    <img class="table-img" id="image_{{ billboard.id }}"
                                                         src="/media/{{ billboard.image }}" alt="">
                                            </td>
                                            <td>
                                                <span class="billboard_link">{{ billboard.link }}</span>
                                                <form class="billboard_link_send" action=""
                                                      style="display: none">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="id"
                                                           value="{{ billboard.id }}">
                                                    <input type="text" name="link"
                                                           value="{{ billboard.link }}">
                                                </form>
                                            </td>
                                            <td>{{ billboard.shows }}</td>
                                            <td>{{ billboard.clicks }}</td>
                                            <td>{{ billboard.get_status_display }}</td>
                                            <td class="text-center action_buttons">
                                                <a href="{% url 'billboard_update' pk=billboard.id %}">изменить</a>
                                            </td>
                                        </tr>
                                        {% empty %}
                                        <tr>
                                        <td colspan="7"><a href="{% url 'billboard_create' %}">Создайте свой рекламный блок для привлечения новых клиентов.</a></td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
        <a href="{% url 'profile:general' %}" class="btn btn-default waves-effect waves-light">
                                                   <span class="btn-label"><i class="fa fa-arrow-left"></i>
                                                   </span>Назад в профиль</a>
    </div>
    </div>
{% endblock %}

ads/templates/billboard/update.html
{% extends 'billboard/create.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block form_title %}Редактирование рекламы {{ form.instance.link }}{% endblock %}
{% block update_css %}
    <link href="{% static 'assets/plugins/switchery/dist/switchery.min.css' %}" rel="stylesheet" />
{% endblock %}
{% block update %}
    <div class="form-group">
        <label for="id_show" class="col-md-2">Показывать рекламу?</label>
    <div class="col-md-8">{{ form.show|attr:'data-plugin:switchery'|attr:'data-color:#81c868' }}</div>
    </div>
{% endblock %}
{% block delete %}
    <a href="{% url 'billboard_delete' pk=form.instance.pk %}" class="btn col-md-offset-5 btn-danger waves-effect waves-light">Удалить</a>
{% endblock %}
{% block update_js %}
    <script src="{% static 'assets/plugins/switchery/dist/switchery.min.js' %}"></script>
{% endblock %}