ads/urls.py
from django.conf.urls import url

from ads import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^register/$', views.registr_view, name='reg'),
    url(r'^adverts/$', views.AdvertList.as_view(), name='advert_list'),
    url(r'^advert_create/$', views.AdvertCreate.as_view(), name='advert_create'),
    url(r'^advert_delete/$', views.advert_delete, name='advert_delete'),
    url(r'^advert_stop/$', views.advert_stop, name='advert_show'),

    url(r'^billboard_stop/$', views.billboard_stop, name='billboard_show'),
    url(r'^billboard_delete/(?P<pk>[0-9]+)/$', views.billboard_delete, name='billboard_delete'),
    url(r'^billboard_create/$', views.billboard_create_view, name='billboard_create'),
    url(r'^billboard_update/(?P<pk>[0-9]+)/$', views.billboard_update, name='billboard_update'),
    url(r'^billboards/$', views.billboard_list, name='billboard_list'),

    url(r'^advert_accept/$', views.advert_accept, name='advert_accept'),
    url(r'^set_cookie/$', views.set_cookie, name='view_cookie'),
    url(r'^advert_favorite/$', views.advert_favorite, name='advert_favorite'),
    url(r'^favorites/$', views.FavoriteView.as_view(), name='favorite_view'),
    url(r'^vip/$', views.vip, name='vip'),
    url(r'^allotted/$', views.allotted, name='allotted'),
    url(r'^up_list/$', views.up_list, name='up_list'),
    url(r'^f_search/$', views.f_search, name='f_search'),
    url(r'^search/$', views.search, name='search'),
    url(r'^click_count/$', views.click_count, name='click_count'),
    url(r'^contacts/$', views.Contacts.as_view(), name='contacts'),
    url(r'^terms/$', views.Terms.as_view(), name='terms'),
    url(r'^advertising/$', views.Advertising.as_view(), name='advertising'),
    url(r'^shop_create/$', views.ShopCreateView.as_view(), name='shop_create'),
    url(r'^shop_status/$', views.shop_status, name='shop_status'),
    url(r'^shops/$', views.ShopListView.as_view(), name='shop_list'),
    url(r'^multiple/$', views.advert_photo_upload, name='advert_photo_upload'),
    url(r'^delete_advert_photo/$', views.advert_photo_delete, name='advert_photo_delete'),
    url(r'^shop_payment/$', views.shop_payment, name='shop_payment'),
    url(r'^metro_load/$', views.metro_load, name='metro_load'),
    url(r'^county_load/$', views.county_load, name='county_load'),
    url(r'^shop/(?P<alias>[\w-]+)/$', views.ShopDetailView.as_view(), name='shop_detail'),
    url(r'^shop/(?P<alias>[\w-]+)/edit/$', views.ShopUpdateView.as_view(), name='shop_update'),
    url(r'^(?P<url_name>.+)/(?P<pk>[0-9]+)/$', views.AdvertDetail.as_view(), name='advert_detail'),
    url(r'^(?P<url_name>.+)/(?P<pk>[0-9]+)/edit/$', views.AdvertUpdate.as_view(), name='advert_update'),
    url(r'^(?P<city>[\w|\W]+)/(?P<category>.+)/$', views.CategoryView.as_view(), name='category_view'),
    url(r'^(?P<city>[\w|\W]+)/$', views.CityFilter.as_view(), name='city_filter'),
]

main/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from main import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('allauth.urls')),
    url(r'^account/profile/', include('authentication.urls', 'profile')),
    url(r'^transaction/', include('transaction.urls')),
    url(r'^', include('ads.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads/models.py
import os

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from .utils import translit


# Create your models here.


class Division(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название раздела')
    url_name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Раздел'
        verbose_name_plural = 'Разделы'

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.url_name = translit(self.name)
        super(Division, self).save()


class Region(models.Model):
    name = models.CharField(max_length=40, unique=True, verbose_name='Название региона')
    url_name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.url_name = translit(self.name)
        super(Region, self).save()

    class Meta:
        verbose_name = 'Регион'
        verbose_name_plural = 'Регионы'


class Metro(models.Model):
    region = models.ForeignKey(Region, verbose_name='Регион')
    name = models.CharField(max_length=60, verbose_name='Название метро')
    url_name = models.CharField(max_length=60)

    class Meta:
        verbose_name = 'Метро'
        verbose_name_plural = 'Метро'
        unique_together = ('region', 'name')

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.url_name = translit(self.name)
        super(Metro, self).save()


class County(models.Model):
    region = models.ForeignKey(Region, verbose_name='Регоин')
    name = models.CharField(max_length=40, verbose_name='Название района')
    url_name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ('region', 'name')
        verbose_name = 'Район'
        verbose_name_plural = 'Районы'

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.url_name = translit(self.name)
        super(County, self).save()


divisions = [
    Division(name='Автомойки, Автосервисы, СТО', url_name=translit('Автомойки, Автосервисы, СТО')),
    Division(name='Автозаправочные станции(АЗС)', url_name=translit('Автозаправочные станции(АЗС)')),
    Division(name='Автосалоны', url_name=translit('Автосалоны')),
    Division(name='Аптеки', url_name=translit('Аптеки')),
    Division(name='Арендный бизнес', url_name=translit('Арендный бизнес')),
    Division(name='Банковская деятельность', url_name=translit('Банковская деятельность')),
    Division(name='Бизнес и Недвижимость за рубежом', url_name=translit('Бизнес и Недвижимость за рубежом')),
    Division(name='Гостиницы, отели, базы отдыха', url_name=translit('Гостиницы, отели, базы отдыха')),
    Division(name='Добыча полезных ископаемых', url_name=translit('Добыча полезных ископаемых')),
    Division(name='Заводы, промышленные помещения', url_name=translit('Заводы, промышленные помещения')),
    Division(name='Коммерческая недвижимость', url_name=translit('Коммерческая недвижимость')),
    Division(name='Медицинские центры и стоматологии', url_name=translit('Медицинские центры и стоматологии')),
    Division(name='Образование', url_name=translit('Образование')),
    Division(name='Продуктовые магазины, супермаркеты', url_name=translit('Продуктовые магазины, супермаркеты')),
    Division(name='Производство', url_name=translit('Производство')),
    Division(name='Развлечения', url_name=translit('Развлечения')),
    Division(name='Рестораны, Кафе, Бары', url_name=translit('Рестораны, Кафе, Бары')),
    Division(name='Салоны красоты', url_name=translit('Салоны красоты')),
    Division(name='Сельское хозяйство', url_name=translit('Сельское хозяйство')),
    Division(name='Сервис и услуги', url_name=translit('Сервис и услуги')),
    Division(name='СМИ', url_name=translit('СМИ')),
    Division(name='Столовые', url_name=translit('Столовые')),
    Division(name='Страховая деятельность', url_name=translit('Страховая деятельность')),
    Division(name='Строительство', url_name=translit('Строительство')),
    Division(name='Телекоммуникации, Интернет - магазины, IT',
             url_name=translit('Телекоммуникации, Интернет - магазины, IT')),
    Division(name='Торговля(оптовая, розничная)', url_name=translit('Торговля(оптовая, розничная)')),
    Division(name='Транспорт и услуги', url_name=translit('Транспорт и услуги')),
    Division(name='Туристический бизнес', url_name=translit('Туристический бизнес')),
    Division(name='Услуги для бизнеса и населения', url_name=translit('Услуги для бизнеса и населения')),
    Division(name='Фитнес центры', url_name=translit('Фитнес центры')),
    Division(name='Прочий бизнес', url_name=translit('Прочий бизнес')),
]

regions = [
    Region(name='Москва', url_name=translit('Москва')),
    Region(name='Санкт-Петербург', url_name=translit('Санкт-Петербург')),
    Region(name='Кемерово', url_name=translit('Кемерово')),
    Region(name='Новокузнецк', url_name=translit('Новокузнецк')),
    Region(name='Ростов-на-Дону', url_name=translit('Ростов-на-Дону')),
    Region(name='Тюмень', url_name=translit('Тюмень')),
    Region(name='Барнаул', url_name=translit('Барнаул')),
    Region(name='Екатеринбург', url_name=translit('Екатеринбург')),
    Region(name='Краснодар', url_name=translit('Краснодар')),
    Region(name='Новосибирск', url_name=translit('Новосибирск')),
    Region(name='Самара', url_name=translit('Самара')),
    Region(name='Уфа', url_name=translit('Уфа')),
    Region(name='Владивосток', url_name=translit('Владивосток')),
    Region(name='Иркутск', url_name=translit('Иркутск')),
    Region(name='Красноярск', url_name=translit('Красноярск')),
    Region(name='Омск', url_name=translit('Омск')),
    Region(name='Сургут', url_name=translit('Сургут')),
    Region(name='Хабаровск', url_name=translit('Хабаровск')),
    Region(name='Волгоград', url_name=translit('Волгоград')),
    Region(name='Казань', url_name=translit('Казань')),
    Region(name='Нижний Новгород', url_name=translit('Нижний Новгород')),
    Region(name='Пермь', url_name=translit('Пермь')),
    Region(name='Томск', url_name=translit('Томск')),
    Region(name='Челябинск', url_name=translit('Челябинск'))
]


def shop_name(instance, filename):
    return '/'.join([instance.alias, filename])


open = 'open'
close = 'close'
status_shop = (
    (open, 'Открытый'),
    (close, 'Закрытый')
)


class Shop(models.Model):
    region = models.ForeignKey(Region, related_name='shops')
    owner = models.OneToOneField(User, related_name='shop', verbose_name='Владелец')
    name = models.CharField(max_length=40, verbose_name='Название магазина')
    alias = models.CharField(max_length=20, unique=True, verbose_name='Ссылка')
    anons = models.CharField(max_length=100, verbose_name='Текст для анонса')
    description = models.TextField(max_length=5000, verbose_name='Описание магазина')
    site = models.URLField(null=True, blank=True, verbose_name='Сайт магазина')
    person = models.CharField(max_length=30, verbose_name='ФИО')
    logo = models.ImageField(upload_to=shop_name, verbose_name='Логотип')
    status = models.CharField(choices=status_shop, max_length=5, verbose_name='Статус')
    video = models.CharField(max_length=50, null=True, blank=True, verbose_name='Видео')
    phones = models.CharField(null=True, blank=True, max_length=17, verbose_name='Телефон')
    mode = models.CharField(max_length=40, null=True, blank=True, verbose_name='График работы')
    address = models.CharField(max_length=255, null=True, blank=True, verbose_name='Адрес')
    skype = models.CharField(max_length=20, null=True, blank=True, verbose_name='Логин skype')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата открытия')
    background = models.ImageField(upload_to=shop_name, null=True, blank=True, verbose_name='Задний фон')
    paid = models.BooleanField(default=False, verbose_name='Оплачен')
    active_days = models.IntegerField(default=0, verbose_name='Количество активных дней')

    class Meta:
        verbose_name = 'Магазин пользователя'
        verbose_name_plural = 'Магазины пользователей'

    def __str__(self):
        return '%s (%s)' % (self.name, self.alias)


class ShopBackground(models.Model):
    image = models.ImageField(upload_to='backgrounds/')

    def image_tag(self):
        return '<img src="%s" style="width: 200px; height: 100px;">' % self.image.url

    image_tag.allow_tags = True

    def __str__(self):
        return self.image.path

    class Meta:
        verbose_name = 'Задний фон магазина'
        verbose_name_plural = 'Задние фоны магазина'


ready = 'ready'
search = 'search'
offer = 'offer'

sectors = (
    (ready, 'Готовый бизнес'),
    (search, 'Поиск инвестиций'),
    (offer, 'Предложения инвесторов'),
)

acts = (
    ('sell', 'Продать'),
    ('buy', 'Купить'),
)

status = (
    ('consideration', 'На рассмотрении'),
    ('rejected', 'Отклонен'),
    ('accepted', 'Разрешен')
)


class PositionManager(models.Manager):
    def max_position(self):
        adverts = Advert.objects.all()
        if adverts:
            position = max(advert.position for advert in adverts)
        else:
            position = 1
        return position


class Favorite(models.Model):
    key = models.CharField(max_length=30, null=True, blank=True)
    user = models.OneToOneField(User, related_name='favorite', null=True, blank=True)


class Advert(models.Model):
    owner = models.ForeignKey(User, related_name='advert', verbose_name='Владелец')
    position = models.IntegerField(null=True, blank=True, default=None)
    region = models.ForeignKey(Region, verbose_name='Регион')

authentication/models.py
from django.contrib.auth.models import User
from django.core import validators
from django.db import models
from ads.models import Region


def content_photo_name(instance, filename):
    return '/'.join([instance.user.username, filename])


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    phone = models.CharField(max_length=16, validators=[
        validators.RegexValidator(r'^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$',
                                  u'Введите правильный номер телефона')])
    partner = models.BooleanField(default=False)
    super_moderator = models.BooleanField(default=False)
    region = models.OneToOneField(Region, related_name='profile_region', null=True, blank=True)
    photo = models.ImageField(upload_to=content_photo_name, null=True, blank=True)
    balance = models.DecimalField(default=0, max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def __str__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)


class MessageGroup(models.Model):
    users = models.ManyToManyField(User, related_name='message_group')


class Message(models.Model):
    user = models.ForeignKey(User, related_name='message')
    group = models.ForeignKey(MessageGroup, related_name='group')
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

ads/templates/advertising.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_title %}Реклама на сайте{% endblock %}
{% block content %}
    {% include 'menu.html' %}
    <div class="myBlocks">
        <div class="container">
            <div class="row">
                <div class="col-md-offset-2 col-md-8" style="margin-top: 50px; margin-bottom: 40px;">
                    <div class="row">
                <div class="col-md-8">
                    <p>
                        Ширина и высота картинки рекламного блока должна быть равна установленным значениям согласно каждому из блоков
                    </p>
                    <p>
                        Стоимость рекламных блоков указана за 1 показ на странице <br>
                        Стоимость клика по рекламному блоку составляет <span class="red">{{ settings.billboard }}</span> рублей
                        <br>
                        Рекламные блоки подбираются случайным образом
                    </p>
                    <div class="col-md-5">
                        <h3>1 блок</h3>
                        <p>Стоимость: <span class="red">{{ settings.block_1 }}</span> рублей</p>
                        <p>Ширина: <span class="red">{{ settings.width_1 }}</span> пикселей</p>
                        <p>Высота: <span class="red">{{ settings.height_1 }}</span> пикселей</p>
                    </div>
                    <div class="col-md-5 col-md-offset-1">
                        <h3>2 блок</h3>
                        <p>Стоимость: <span class="red">{{ settings.block_2 }}</span> рублей</p>
                        <p>Ширина: <span class="red">{{ settings.width_2 }}</span> пикселей</p>
                        <p>Высота: <span class="red">{{ settings.height_2 }}</span> пикселей</p>
                    </div>
                    <div class="col-md-5">
                        <h3>3 блок</h3>
                        <p>Стоимость: <span class="red">{{ settings.block_3 }}</span> рублей</p>
                        <p>Ширина: <span class="red">{{ settings.width_3 }}</span> пикселей</p>
                        <p>Высота: <span class="red">{{ settings.height_3 }}</span> пикселей</p>
                    </div>
                    <div class="col-md-5 col-md-offset-1">
                        <h3>4 блок</h3>
                        <p>Стоимость: <span class="red">{{ settings.block_4 }}</span> рублей</p>
                        <p>Ширина: <span class="red">{{ settings.width_4 }}</span> пикселей</p>
                        <p>Высота: <span class="red">{{ settings.height_4 }}</span> пикселей</p>
                    </div>
                </div>
                    <div class="col-md-4">
                        <img src="{% static 'images/advert.png' %}" alt="" style="width: 100%">
                    </div>
                        </div>
                </div>
                <div class="col-md-6 col-md-offset-3">
                    <h4 class="bold m-b-20">Есть вопросы по поводу рекламы? Пишите.</h4>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_email">Ваш email:</label>
                            <input id="id_email" type="email" class="form-control" name="mail" required>
                        </div>
                        <div class="form-group">
                            <label for="id_text">Ваше имя:</label>
                            <input id="id_text" type="text" class="form-control" name="name" required>
                        </div>
                        <div class="form-group">
                            <label for="id_message">Сообщение:</label>
                            <textarea name="message" id="id_message" class="form-control" required></textarea>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-default waves-effect waves-light">Отправить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ads/templates/city_filter.html
{% extends 'base.html' %}
{% block content %}
    {% if billboard %}
        <img style="width: 100%; height: 50px" src="/media/{{ billboard.image }}" alt="">
    {% endif %}
{{ adverts }}
{% endblock %}

ads/templates/contacts.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_title %}Контакты{% endblock %}
{% block content %}
    {% include 'menu.html' %}
    <div class="myBlocks">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <h4 class="bold m-b-20">Сообщение для администрации</h4>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_email">Ваш email:</label>
                            <input id="id_email" type="email" class="form-control" name="mail" required>
                        </div>
                        <div class="form-group">
                            <label for="id_text">Ваше имя:</label>
                            <input id="id_text" type="text" class="form-control" name="name" required>
                        </div>
                        <div class="form-group">
                            <label for="id_message">Сообщение:</label>
                            <textarea name="message" id="id_message" class="form-control" required></textarea>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-default waves-effect waves-light">Отправить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ads/templates/favorite.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_title %}Избранное{% endblock %}
{% block content %}
    <div class="favorite-wrap full-height">
        {% include 'menu.html' %}
        <div class="">
            <div class="container">
                {% if favorite.adverts.all %}
                    <h4 class="favorite-title">Ваши избранные объявления</h4>
                    {% for advert in favorite.adverts.all %}
                        <div class="item rows" data-cost="{{ advert.cost }}" data-date="{{ advert.date }}">
                            <div class="advert-item clearfix">
                                <div class="advert-item-count-img">
                                    <span title="количество фотографий объявления">{{ advert.photo.count }}</span>
                                </div>
                                <div class="advert-item-name">
                                    <a href="{% url 'advert_detail' url_name=advert.url_name pk=advert.pk %}">
                                        <span>{{ advert.title }}</span>
                                    </a>
                                </div>
                                <div class="preview-buttons">
                                        <span data-id="{{ advert.pk }}" class="favorite">
                                            <i class="fa fa-star fav"></i>
                                        </span>
                                    <span>
                                        <i class="fa fa-eye"></i> {{ advert.visitors }}
                                    </span>
                                </div>
                                <div class="advert-item-cost" data-cost="{{ advert.cost }} руб"></div>
                                <div class="advert-item-date">
                                    <span>Размещено: {{ advert.date }}</span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <h4 class="favorite-title">У Вас нет избранных объявлений</h4>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'assets/plugins/notifyjs/dist/notify.min.js' %}"></script>
    <script src="{% static 'assets/plugins/notifications/notify-metro.js' %}"></script>
    <script>
        $(window).resize(function () {
            var h = $(window).height();
            var n = $('nav').height();
            $('.full-height').css({'min-height': h - n});
        });
        $(window).trigger('resize');
        function abc2(n) {
            n = new Array(5 - n.length % 3).join("U") + n;
            return n.replace(/([0-9U]{3})/g, "$1 ").replace(/U/g, "");
        }
        $.each($('.advert-item-cost'), function (index, value) {
            $(value).text(abc2($(value).attr('data-cost')))
        });
        $('.favorite').click(function () {
            var fav = $(this);
            $.ajax({
                type: 'POST',
                url: '{% url 'advert_favorite' %}',
                data: {'csrfmiddlewaretoken': '{{ csrf_token }}', 'id': $(this).attr('data-id')},
                success: function (data) {
                    if (data == 'del') {
                        $.Notification.notify('success', 'top left', 'Удалено из избранного!')
                    } else {
                        $.Notification.notify('success', 'top left', 'Добавлено в избранное!')
                    }
                    fav.find('i.fav').toggleClass('fa-star-o').toggleClass('fa-star');
                }
            })
        });
    </script>
{% endblock %}

ads/templates/shop_create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block head_title %}{% if object %}Редактирование{% else %}Создание{% endif %} магазина {% if object %} - {{ object.owner.first_name }} {{ object.owner.last_name }}{% endif %}{% endblock %}
{% block content %}
    {% include 'menu.html' %}
    <div class="row m-0">
        <div class="card-box col-md-10 col-md-offset-1">
            <div class="col-md-12">
                <span class="header-title">{% if object %}Редактирование{% else %}Создание{% endif %} магазина</span>
                <hr class="m-t-10 m-b-10">
            </div>
            <div class="col-sm-9">
                <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group col-sm-12">
                        <label for="id_name">Название магазина: *</label>
                        {{ form.name|add_class:'form-control' }}
                        {{ form.name.errors }}
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="id_alias">URL магазина: * <span class="normal">Например: <span class="bold text-red">http://biznesdesk.ru/magazin/</span> - где <span class="bold text-red">magazin</span> URL магазина</span></label>
                        {{ form.alias|add_class:'form-control' }}
                        {{ form.alias.errors }}
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="id_region">Выберите регион: *</label>
                        {{ form.region|add_class:'form-control' }}
                        {{ form.region.errors }}
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="id_anons">Анонс</label>
                        {{ form.anons|add_class:'form-control'|attr:'placeholder:Поле для текста' }}
                        {{ form.anons.errors }}
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="id_description">Подробности: *</label>
                        {{ form.description|add_class:'form-control'|attr:'placeholder:Поле для текста' }}
                        {{ form.description.errors }}
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="id_site">Ссылка на сайт:</label>
                        {{ form.site|add_class:'form-control' }}
                        {{ form.site.errors }}
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="id_person">Контактное лицо:</label>
                        {% if form.person.value %}
                        {{ form.person|add_class:'form-control'|attr:'readonly' }}
                        {% else %}
                            {{ form.person|add_class:'form-control' }}
                        {% endif %}
                        {{ form.person.errors }}
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="id_logo">Лого: *</label>
                        {{ form.logo|add_class:'filestyle'|attr:'data-buttonname:btn-primary' }}
                        {{ form.logo.errors }}
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="id_site">Ссылка на видео с YouTube:</label>
                        {{ form.video|add_class:'form-control' }}
                        {{ form.video.errors }}
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="id_site">Телефон:</label>
                        {{ form.phones|add_class:'form-control'|attr:'data-mask:8 (999) 999-9999' }}
                        <span class="font-13 text-muted">Пример: 8 (495) 999-9999</span>
                        {{ form.phones.errors }}
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="id_site">Режим работы:</label>
                        {{ form.mode|add_class:'form-control'|attr:'data-mask:с 99-99 до 99-99' }}
                        <span class="font-13 text-muted">Пример: с 9:00 до 18:00</span>
                        {{ form.mode.errors }}
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="id_site">Адрес:</label>
                        {{ form.address|add_class:'form-control' }}
                        {{ form.address.errors }}
                    </div>
                    <div class="form-group col-sm-12">
                        <label for="id_site">Skype:</label>
                        {{ form.skype|add_class:'form-control' }}
                        {{ form.skype.errors }}
                    </div>
                <div style="margin-bottom: 20px;" class="backgrounds">
                    {% for image in images %}
                        <img style="width: 100px; padding: 3px"
                             class="{% if image.image == object.background %}active{% endif %} image"
                             src="{{ image.image.url }}" alt="" data-id="{{ image.id }}">
                    {% endfor %}
                    {{ form.image }}
                    </div>
                    <button class="btn btn-rounded btn-default waves-effect waves-light" type="submit">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                </form>
            </div>
                                        <div class="form-group col-md-12 clearfix">
                                    <label class="col-lg-12 control-label ">(*) Обязательное поле</label>
                                </div>
            <div class="col-sm-3">

            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'assets/plugins/bootstrap-filestyle/src/bootstrap-filestyle.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/plugins/bootstrap-inputmask/bootstrap-inputmask.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/plugins/autoNumeric/autoNumeric.js' %}" type="text/javascript"></script>
    <script>
    $('.image').click(function () {
        if ($(this).hasClass('active')){
            $(this).removeClass('active');
            $('#id_image').val(null)
        } else {
            $('.image.active').removeClass('active');
            $(this).addClass('active');
            $('#id_image').val($(this).attr('data-id'))
        }
    })
    </script>
{% endblock %}

ads/templates/upload_result.html
{% load staticfiles %}{{ error }}
    {% for image in images %}
    <div class="preview" id="advert_{{ image.id }}">
        <span class="delete" data-id="{{ image.id }}">X</span>
        <img src="/media/{{ image.photo }}" alt="">
    </div>
    {% endfor %}